/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Salud del monitor: montaje de `runs_dir`, frescura del poller, clientes WS.
         *
         *     `runs_mounted` existe porque `runs/` y `calculations/` son symlinks a un
         *     volumen externo. Sin esta señal, "el disco está desmontado" y "no hay jobs"
         *     se ven exactamente igual desde el cliente.
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Jobs
         * @description Jobs paginados, con filtro y orden.
         *
         *     Devolver los ~2500 snapshots enteros en cada carga eran varios MB de JSON.
         */
        get: operations["list_jobs_api_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/converged": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Converged
         * @description Lista los primeros N jobs convergidos ordenados por fórmula.
         */
        get: operations["list_converged_api_jobs_converged_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/ping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ping
         * @description Lectura instantánea del log actual — no usa caché.
         */
        get: operations["ping_api_jobs__job_id__ping_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Stats
         * @description Igual que GET /api/jobs/{job_id} pero fuerza re-parseo del disco.
         */
        get: operations["get_stats_api_jobs__job_id__stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Job Log
         * @description Cola del log del job. `available` lista las etiquetas seleccionables.
         */
        get: operations["job_log_api_jobs__job_id__log_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/traces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Job Traces Endpoint
         * @description Series SCF por etiqueta y resumen de los frames etiquetados con DFT.
         */
        get: operations["job_traces_endpoint_api_jobs__job_id__traces_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/metadata": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Job Metadata Endpoint
         * @description metadata.json y status.json del job, más el inventario de artefactos.
         */
        get: operations["job_metadata_endpoint_api_jobs__job_id__metadata_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Summary */
        get: operations["summary_api_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/system": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * System Metrics
         * @description Temperaturas, uso de CPU y RAM en tiempo real.
         */
        get: operations["system_metrics_api_system_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/system/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * System History
         * @description Serie reciente de CPU, RAM y temperatura, para las sparklines.
         *
         *     `/api/system` solo da el instante actual.
         */
        get: operations["system_history_api_system_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/statusfull": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Statusfull Report
         * @description Devuelve el reporte statusfull (detalle SCF por job activo) como lista de mensajes.
         */
        get: operations["statusfull_report_api_statusfull_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notify/converged": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Notify Converged
         * @description Envía a Telegram los primeros N convergidos que quepan en 4096 chars.
         */
        post: operations["notify_converged_api_notify_converged_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/status/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Status Report
         * @description Devuelve el reporte STATUS completo como texto.
         */
        get: operations["status_report_api_status_report_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notify/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Notify Status
         * @description Envía reporte STATUS completo a Telegram ahora.
         */
        post: operations["notify_status_api_notify_status_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/batches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Batches Endpoint
         * @description Batches con su recuento por estado, throughput y ETA.
         */
        get: operations["list_batches_endpoint_api_batches_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/kill": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Kill Job Endpoint
         * @description Detiene los procesos de un job. Acción destructiva: queda auditada.
         */
        post: operations["kill_job_endpoint_api_jobs__job_id__kill_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Retry Job Endpoint
         * @description Devuelve un job fallido a la cola para que el runner lo recoja.
         */
        post: operations["retry_job_endpoint_api_jobs__job_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/batches/{batch_id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Batch Endpoint
         * @description Lanza el runner de un batch. Arranca un proceso: queda auditado.
         */
        post: operations["start_batch_endpoint_api_batches__batch_id__start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/structures": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Structures Endpoint
         * @description Estructuras disponibles: fases de referencia, top-8 y las de cada job.
         */
        get: operations["list_structures_endpoint_api_structures_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/structures/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Structure Content
         * @description Estructura en CIF. Los structures/*.json de ASE se convierten al vuelo.
         */
        get: operations["structure_content_api_structures_content_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Reports Endpoint
         * @description Reportes Markdown y galerías declaradas en los visualization_manifest.json.
         */
        get: operations["list_reports_endpoint_api_reports_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/document": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Report Document */
        get: operations["report_document_api_reports_document_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/figure": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Report Figure
         * @description Sirve una figura. Muchas están en .gitignore y pueden no existir.
         */
        get: operations["report_figure_api_reports_figure_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/screening/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Screening Config
         * @description Cotas de la cascada y disponibilidad real de cada tier.
         */
        get: operations["screening_config_api_screening_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/screening/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Screening Run
         * @description Arranca la cascada en segundo plano y devuelve el identificador.
         *
         *     Tarda minutos: se consulta el progreso en /api/screening/runs/{run_id}.
         */
        post: operations["screening_run_api_screening_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/screening/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Screening Runs */
        get: operations["screening_runs_api_screening_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/screening/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Screening Run Detail */
        get: operations["screening_run_detail_api_screening_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/candidates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Candidates
         * @description Candidatos del generador BUHO.
         *
         *     `source` indica de dónde salieron: el CSV del generador si está disponible,
         *     o los metadata.json de los jobs como alternativa.
         */
        get: operations["list_candidates_api_candidates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Models
         * @description Métricas de los surrogates y estado de carga del modelo de bandgap.
         */
        get: operations["list_models_api_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ml/predict": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ml Predict
         * @description Bandgap predicho con incertidumbre bootstrap para una composición ABX3.
         */
        post: operations["ml_predict_api_ml_predict_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ml/top8": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ml Top8
         * @description Predicción ML frente a DFT y experimento para los 8 candidatos top.
         */
        get: operations["ml_top8_api_ml_top8_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notify/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Notify Test */
        post: operations["notify_test_api_notify_test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agent/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Agent Health */
        get: operations["agent_health_api_agent_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agent/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Agent Chat */
        post: operations["agent_chat_api_agent_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agent/proposals/{proposal_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve Proposal */
        post: operations["approve_proposal_api_agent_proposals__proposal_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agent/proposals/{proposal_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject Proposal */
        post: operations["reject_proposal_api_agent_proposals__proposal_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AgentChatRequest */
        AgentChatRequest: {
            /** Message */
            message: string;
            /**
             * History
             * @default []
             */
            history: components["schemas"]["AgentMessage"][];
            /** Job Id */
            job_id?: string | null;
            /**
             * Structured
             * @default false
             */
            structured: boolean;
        };
        /** AgentChatResponse */
        AgentChatResponse: {
            /** Ok */
            ok: boolean;
            /** Model */
            model: string;
            /** Message */
            message: string;
            /** Structured */
            structured?: {
                [key: string]: unknown;
            } | null;
            /** Tool Rounds */
            tool_rounds: number;
            /** Tool Results */
            tool_results: components["schemas"]["AgentToolResult"][];
            /**
             * Proposal Ids
             * @default []
             */
            proposal_ids: string[];
        };
        /** AgentHealthResponse */
        AgentHealthResponse: {
            /** Enabled */
            enabled: boolean;
            /** Provider */
            provider: string;
            /** Ok */
            ok: boolean;
            /** Base Url */
            base_url: string;
            /** Model */
            model: string;
            /**
             * Model Present
             * @default false
             */
            model_present: boolean;
            /** Manage Service */
            manage_service: boolean;
            /**
             * Allow Writes
             * @default false
             */
            allow_writes: boolean;
            /** Models Dir */
            models_dir: string;
            /** Revive Repo */
            revive_repo: string;
            /** Version */
            version?: string | null;
            /** Error */
            error?: string | null;
        };
        /** AgentMessage */
        AgentMessage: {
            /**
             * Role
             * @enum {string}
             */
            role: "system" | "user" | "assistant" | "tool";
            /** Content */
            content: string;
        };
        /** AgentProposalResponse */
        AgentProposalResponse: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Created At */
            created_at: number;
            /** Status */
            status: string;
            /** Command */
            command?: string | null;
            /** Diff */
            diff?: string | null;
            /** Rationale */
            rationale?: string | null;
            /**
             * Metadata
             * @default {}
             */
            metadata: {
                [key: string]: unknown;
            };
            /**
             * Executed
             * @default false
             */
            executed: boolean;
        };
        /** AgentToolResult */
        AgentToolResult: {
            /** Name */
            name: string;
            /**
             * Arguments
             * @default {}
             */
            arguments: {
                [key: string]: unknown;
            };
            /** Ok */
            ok: boolean;
            /** Data */
            data?: unknown | null;
            /** Error */
            error?: string | null;
            /** Status Code */
            status_code?: number | null;
        };
        /** AuthState */
        AuthState: {
            /** Authenticated */
            authenticated: boolean;
            /** Auth Enabled */
            auth_enabled: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Ok */
            ok: boolean;
            /** Version */
            version: string;
            paths: components["schemas"]["PathsInfo"];
            platform: components["schemas"]["PlatformInfo"];
            /** Runs Dir */
            runs_dir: string;
            /** Runs Mounted */
            runs_mounted: boolean;
            /** Nearest Existing Path */
            nearest_existing_path: string;
            /** N Jobs Tracked */
            n_jobs_tracked: number;
            /** Last Poll At */
            last_poll_at: number | null;
            /** Last Poll Age Sec */
            last_poll_age_sec: number | null;
            /** Poll Interval Sec */
            poll_interval_sec: number;
            /** Ws Clients */
            ws_clients: number;
        };
        /** JobPage */
        JobPage: {
            /** Items */
            items: components["schemas"]["JobStatus"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** JobStatus */
        JobStatus: {
            /** Job Id */
            job_id: string;
            /** Formula */
            formula: string;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "running" | "converged" | "partial" | "failed" | "stalled" | "oscillating" | "stopped" | "skipped_duplicate" | "unknown";
            /** Pid */
            pid?: number | null;
            /** Start Time */
            start_time?: string | null;
            /** Elapsed Min */
            elapsed_min?: number | null;
            /** Mpi Cores */
            mpi_cores?: number | null;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Token */
            token: string;
        };
        /** MetricsHistoryResponse */
        MetricsHistoryResponse: {
            /** Samples */
            samples: {
                [key: string]: unknown;
            }[];
            /** Interval Sec */
            interval_sec: number;
        };
        /** PathsInfo */
        PathsInfo: {
            /** Frozen */
            frozen: boolean;
            /** Bundle Root */
            bundle_root: string;
            /** Data Root */
            data_root: string;
            /** Config Dir */
            config_dir: string;
        };
        /** PingResponse */
        PingResponse: {
            /** Job Id */
            job_id: string;
            /** Alive */
            alive: boolean;
            /** Current Step */
            current_step?: number | null;
            /** Step Type */
            step_type?: string | null;
            /** Energy Ev */
            energy_ev?: number | null;
            /** Fmax Ev Ang */
            fmax_ev_ang?: number | null;
            /** Memory Rss Mb */
            memory_rss_mb?: number | null;
            /** T Iter S */
            t_iter_s?: number | null;
            /** Eta Min */
            eta_min?: number | null;
            /** Log Last Line */
            log_last_line?: string | null;
            /**
             * Status
             * @default unknown
             * @enum {string}
             */
            status: "pending" | "running" | "converged" | "partial" | "failed" | "stalled" | "oscillating" | "stopped" | "skipped_duplicate" | "unknown";
        };
        /** PlatformInfo */
        PlatformInfo: {
            /** Os */
            os: string;
            /** Frozen */
            frozen: boolean;
            /** Hardware Temps */
            hardware_temps: boolean;
            /** Runner Launch */
            runner_launch: boolean;
            /** Runner Python */
            runner_python?: string | null;
            /**
             * Auto Advance
             * @default true
             */
            auto_advance: boolean;
        };
        /** PredictRequest */
        PredictRequest: {
            /** A */
            A: string;
            /** B */
            B: string;
            /** X */
            X: string;
            /** A Lat */
            a_lat?: number | null;
            /** E Mace Ev Atom */
            e_mace_ev_atom?: number | null;
            /** Band Gap Gga Ev */
            band_gap_gga_ev?: number | null;
            /** Eform Ev Atom */
            eform_ev_atom?: number | null;
            /** Material */
            material?: string | null;
        };
        /** ScreeningRunRequest */
        ScreeningRunRequest: {
            /**
             * Batch Id
             * @default 0
             */
            batch_id: number;
            /**
             * N Candidates
             * @default 200
             */
            n_candidates: number;
            /** Use Mlff */
            use_mlff?: boolean | null;
        };
        /** StatsResponse */
        StatsResponse: {
            /** Job Id */
            job_id: string;
            /** Formula */
            formula: string;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "running" | "converged" | "partial" | "failed" | "stalled" | "oscillating" | "stopped" | "skipped_duplicate" | "unknown";
            /** Pid */
            pid?: number | null;
            /** Start Time */
            start_time?: string | null;
            /** Elapsed Min */
            elapsed_min?: number | null;
            /** Mpi Cores */
            mpi_cores?: number | null;
            /**
             * Energy History
             * @default []
             */
            energy_history: number[];
            /**
             * Fmax History
             * @default []
             */
            fmax_history: number[];
            /**
             * Scf Iter History
             * @default []
             */
            scf_iter_history: number[];
            /**
             * N Fire Steps
             * @default 0
             */
            n_fire_steps: number;
            /**
             * N Scf Iters
             * @default 0
             */
            n_scf_iters: number;
            /**
             * Is Oscillating
             * @default false
             */
            is_oscillating: boolean;
            /** Stall Minutes */
            stall_minutes?: number | null;
            /** Final Energy Ev */
            final_energy_ev?: number | null;
        };
        /** SummaryResponse */
        SummaryResponse: {
            /** N Pending */
            n_pending: number;
            /** N Running */
            n_running: number;
            /** N Converged */
            n_converged: number;
            /** N Failed */
            n_failed: number;
            /** N Stalled */
            n_stalled: number;
            /** N Oscillating */
            n_oscillating: number;
            /**
             * N Skipped Duplicate
             * @default 0
             */
            n_skipped_duplicate: number;
            /** Total */
            total: number;
            /** Convergence Rate */
            convergence_rate?: number | null;
        };
        /** SysMetricsResponse */
        SysMetricsResponse: {
            /** Cpu Percent */
            cpu_percent: number;
            /** Cpu Per Core */
            cpu_per_core: number[];
            /** Ram Used Gb */
            ram_used_gb: number;
            /** Ram Total Gb */
            ram_total_gb: number;
            /** Ram Percent */
            ram_percent: number;
            /** Pkg Temps */
            pkg_temps: number[];
            /** Core Temp Max */
            core_temp_max: number;
            /** Nvme Temp */
            nvme_temp: number | null;
            /** Gpu Temps */
            gpu_temps: number[];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    me_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthState"];
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthState"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_jobs_api_jobs_get: {
        parameters: {
            query?: {
                /** @description Estado a filtrar; admite lista separada por comas. */
                status?: string | null;
                /** @description Subcadena buscada en la fórmula o el job_id. */
                q?: string | null;
                sort?: string;
                desc?: boolean;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_converged_api_jobs_converged_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStatus"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ping_api_jobs__job_id__ping_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PingResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_stats_api_jobs__job_id__stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    job_log_api_jobs__job_id__log_get: {
        parameters: {
            query?: {
                /** @description Sub-cálculo; por defecto el primero disponible. */
                label?: string | null;
                /** @description Últimas N líneas. */
                tail?: number;
            };
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    job_traces_endpoint_api_jobs__job_id__traces_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    job_metadata_endpoint_api_jobs__job_id__metadata_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    summary_api_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SummaryResponse"];
                };
            };
        };
    };
    system_metrics_api_system_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SysMetricsResponse"];
                };
            };
        };
    };
    system_history_api_system_history_get: {
        parameters: {
            query?: {
                /** @description Ventana en minutos. */
                minutes?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricsHistoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    statusfull_report_api_statusfull_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    notify_converged_api_notify_converged_post: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    status_report_api_status_report_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    notify_status_api_notify_status_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    list_batches_endpoint_api_batches_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    kill_job_endpoint_api_jobs__job_id__kill_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_job_endpoint_api_jobs__job_id__retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_batch_endpoint_api_batches__batch_id__start_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                batch_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_structures_endpoint_api_structures_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    structure_content_api_structures_content_get: {
        parameters: {
            query: {
                /** @description Identificador de /api/structures (repo:… o job:…). */
                id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_reports_endpoint_api_reports_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    report_document_api_reports_document_get: {
        parameters: {
            query: {
                /** @description Ruta relativa al repo, dentro de reports/ o imagenes/. */
                path: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    report_figure_api_reports_figure_get: {
        parameters: {
            query: {
                /** @description Ruta relativa al repo de una figura. */
                path: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    screening_config_api_screening_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    screening_run_api_screening_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScreeningRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    screening_runs_api_screening_runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    screening_run_detail_api_screening_runs__run_id__get: {
        parameters: {
            query?: {
                /** @description Filas del ranking a devolver. */
                limit?: number;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_candidates_api_candidates_get: {
        parameters: {
            query?: {
                /** @description Subcadena en la fórmula. */
                q?: string | null;
                /** @description pure/A_mixed/B_mixed/X_mixed, coma. */
                generation_mode?: string | null;
                /** @description Familia del sitio B, coma. */
                b_family?: string | null;
                /** @description Haluro dominante, coma. */
                halide?: string | null;
                sort?: string;
                desc?: boolean;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_models_api_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    ml_predict_api_ml_predict_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PredictRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ml_top8_api_ml_top8_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    notify_test_api_notify_test_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    agent_health_api_agent_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentHealthResponse"];
                };
            };
        };
    };
    agent_chat_api_agent_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentChatResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_proposal_api_agent_proposals__proposal_id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                proposal_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentProposalResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_proposal_api_agent_proposals__proposal_id__reject_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                proposal_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentProposalResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
